### ISSUE TITLE
Commanfo doctrine_cli/convert_mapping_from_db no funciona

### ISSUE THREAD

**Issue by manukieli** [egarofalo/ci-doctrine#1]
Hola el siguiente comando `doctrine_cli/convert_mapping_from_db` no me funicona.
Me devuelve el siguiente mensaje de error:
**Could not open input file: vendor/bin/doctrine**
He modificado la linea 106 del fichero Doctrine_cli.php de la siguiente forma:
`$cmd = "php " . APPPATH . "vendor/bin/doctrine.php {$cmd}";`
Pero no esta haciendo nada.

Me devuelve desde la consola el siguiente mensaje:

dir=$(d=${0%[/\\]*}; cd "$d" > /dev/null; cd "../doctrine/orm/bin" && pwd)
        # See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi
dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/doctrine.php" "$@"

**Comment by egarofalo** [comment]
Hola, el problema es que no esta encontrando la consola de doctrine en la ubicación esa. Copiaste el archivo <code>cli-config.php</code> al mismo nivel de la carpeta vendor? O sea en el mismo nivel del árbol de directorios (<code>application, system, vendor, index.php, cli-config.php...</code>). Acordate que para que funcione la consola de Doctrine tenes que copiar ese archivo en dicha ubicación.
Probaste con los otros comandos? Por otro lado deja la linea 106 al igual que estaba antes porque ejecuta la consola correctamente. De todas maneras si tu equipo tiene Windows se va a ejecutar la línea 104. Verifica todo eso y escríbeme para ver si funcionó o no. Saludos!

**Comment by manukieli** [comment]
Gracias por contestar.
He dejado el fichero Doctrine_cli.php como estaba y si que tengo el fichero cli-config.php en el path que dices.
Pero sigue devolviendo el mismo error: `Could not open input file: vendor/bin/doctrine.php`
Estoy usando Linux (Centos)

**Comment by egarofalo** [comment]
Te comento que lo he probado en cygwin y me funcionó correctamente, pero no lo he probado en un equipo con linux. Prueba modificando la línea 106 por el siguiente código:
<code>$cmd = "vendor/bin/doctrine {$cmd}";</code>
Si funciona o no escríbeme por favor, así corrijo el error y genero una nueva versión de la librería.

**Comment by manukieli** [comment]
Hola, lo acabo de probar y me devuelve el siguiente mensaje de error:
`sh: vendor/bin/doctrine.php: No such file or directory`

**Comment by egarofalo** [comment]
Lo que esta pasando es que no encuentra el script <code>vendor/bin/doctrine.php</code> que es el necesario para ejecutar la consola de doctrine.  En primer lugar verifica que dicho archivo exista y si no instala doctrine con el comando <code>composer require doctrine/orm</code> o proba también actualizando el package con <code>composer update doctrine/orm</code>.

**Comment by manukieli** [comment]
Si, el fichero existe, pero creo que el path no es correcto.
Doctrine ya está instalado.
Voy a probar el update.

**Comment by manukieli** [comment]
Lo que ocurre con la instalacion del paquete y de la actualizacion es que me lo instala dentro de la carpeta application, por los cual tengo la siguiente estructura:
├── application/
│	└── application/
│		├── libraries
│	 	│   └── doctrine/
│		│		└── ..
│		└── ...
├── vendor/
│   ├── bin/
│   ├── doctrine/
│	│	└── ...
│	└── ...
└── ...

**Comment by egarofalo** [comment]
Si vez que se complica utilizando el controlador <code>docrine_cli</code>, prueba ejecutando la consola de Doctrine de forma manual. Mira los comandos definidos en el controlador para que veas como se ejecutan. Te paso el link de la doc de doctrine donde ejecuta la consola <code>http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/getting-started.html#generating-the-database-schema</code>

**Comment by egarofalo** [comment]
La libreria <b>ci-doctrine</b> se instala automáticamente en la carpeta <code>libraries/doctrine</code>, ya que el tipo de paquete en composer es <b>codeigniter-library</b> por lo tanto esta estructura de directorios es correcta. Lo único que veo extraño es que tenes la carpeta <code>application/application</code>.

**Comment by manukieli** [comment]
Si, la estructura `application/application` se obtiene con la instalacion de tu paquete, pero desde el paquete de doctrine se instala en vendor.

**Comment by egarofalo** [comment]
Que raro porque eso no debería pasar. Te comento, el paquete doctrine dentro de la carpeta <code>vendor</code> es el paquete <code>doctrine/orm</code> y el paquete instalado en la carpeta <code>libraries</code> es el que desarrolle yo <code>co-developers/ci-doctrine</code> que tiene como dependencia a <code>doctrine/orm</code>. Por eso esa estructura de carpetas es correcta. Lo que si no debería pasar es que cree una subcarpeta application dentro de application. Es muy raro. De hecho lo instale varias veces en diferentes proyectos y jamas me paso. En que nivel de directorio ejecutas el comando de composer?

**Comment by manukieli** [comment]
Creo que acabas de aclararme el tema, tengo composer.json dentro de la carpeta application y la carpeta vendor con todas sus dependencias se encuentran dentro de dicha carpeta tambien (application).
Probaré dejando composer en la raíz del proyecto.

**Comment by egarofalo** [comment]
Aaaa clarooo!!! Realice el siguiente, elimina dicha carpeta application, copia el archivo composer.json al raiz del proyecto, y desinstalá todos los paquetes o borra de forma manual todos lso archivos generados por la instalacion del paquete, y la carpeta vendor tambien y proba nuevamente desde 0, pero ejecuando el comando <code>composer require co-developers/ci-doctrine</code> en el mismo nivel del controlador frontal <code>index.php</code> de CodeIgniter, o sea, en la raíz del proyecto.

**Comment by egarofalo** [comment]
Si borras todo, no te olvides de eliminar el archivo composer.json también si instalaste CodeIgniter manualmente sin utilizar composer.

**Comment by egarofalo** [comment]
Otra cosa que me acabo de dar cuenta, no te olvides de modificar el archivo <code>application/config/config.php</code> e indicarle el path del archivo <code>autoload.php</code> de Composer. No te olvides que si no indicas la ruta del autoload, CodeIgniter lo busca por default en la carpeta <code>application/vendor</code>.
Debes dejar la línea 139 de la siguiente manera: <code>$config['composer_autoload'] = 'vendor/autoload.php';</code>.

**Comment by egarofalo** [comment]
Comentame por favor si ya te funcionó. En caso de que no funcione lo seguimos investigando y me pondré a trabajar para correjirlo.

**Comment by manukieli** [comment]
Ok, ya he movido la carpeta vendor en la raiz del proyecto y he instalado el paquete y todo se instala de forma correcta.
No obstante, el siguiente comando sigue sin funcionar:
`php index.php doctrine_cli/convert_mapping_from_db`

Me devuelve el siguiente mensaje de error:

dir=$(d=${0%[/\\]*}; cd "$d" > /dev/null; cd "../doctrine/orm/bin" && pwd)
        # See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi
dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/doctrine.php" "$@"

Pero ejecutando el commando directo de Doctrine, si que me crea las entidades en el directorio ORM/Entity

**Comment by egarofalo** [comment]
Muy bien, modifica nuevamente la línea 106 <code>$cmd = "php vendor/bin/doctrine.php {$cmd}";</code> por lo siguiente <code>$cmd = "vendor/bin/doctrine {$cmd}";</code> y si funciona, hay que realizar la misma modificación para el resto de las acciones. Probalo y decime.

**Comment by manukieli** [comment]
Sigue sin funcionar.

Saludos cordiales,

El 9 de noviembre de 2017, 15:23, Edgardo Garofalo <notifications@github.com

**Comment by egarofalo** [comment]
Bueno gracias por tu tiempo, utiliza la consola de doctrine de forma manual. Voy a probarlo en linux y cuando lo solucione te escribo, saludos.

**Comment by manukieli** [comment]
Gracias por el tuyo para aclararme el tema.
Me has sido de GRAN ayuda.

**Comment by egarofalo** [comment]
Buenas tardes, te comento que monte una maquina virtual con Debian 9 y genere un proyecto en Codeginiter, instale ci-dcotrine y probe los comandos del controlador Doctrine_cli y funcionan todos correctamente, inclusive el que te estaba fallando. Tal vez debe tener problemas en la disto Centos. Verifica si tenes algún problema en la configuración de la libreria. Espero que lo puedas solucionar, sldos!

**Comment by manukieli** [comment]
Hola, Ok, muchas gracias por el tiempo pasado en mirarlo. Le echaré un vistazo. Saludos.
