### ISSUE TITLE
Class 'Symfony\Component\Yaml\Yaml' not found

### ISSUE THREAD

**Issue by mtnsosa** [egarofalo/ci-doctrine#2]
Hi, when i try to run my CI app after instal ci-doctrine, i get this error:

```
An uncaught Exception was encountered
Type: Error

Message: Class 'Symfony\Component\Yaml\Yaml' not found

Filename: C:\xampp\htdocs\redsocial\application\libraries\doctrine\Doctrine.php

Line Number: 26

Backtrace:

File: C:\xampp\htdocs\redsocial\application\libraries\doctrine\Doctrine.php
Line: 21
Function: setEntityManager

File: C:\xampp\htdocs\redsocial\application\controllers\Home.php
Line: 8
Function: __construct

File: C:\xampp\htdocs\redsocial\index.php
Line: 315
Function: require_once
```
hope you can help me.

**Comment by egarofalo** [comment]
Check if you set the composer autoload in the <code>application/config.php</code> file. This is in the line 141 of the <code>config.php</code> file.

**Comment by mtnsosa** [comment]
It is in last line of `application/config.php`. Line #132

**Comment by egarofalo** [comment]
Yes, it depends on the framework version. Let me know if it worked.

**Comment by mtnsosa** [comment]
still doesnt work :c

**Comment by egarofalo** [comment]
Ok, try replace this <code>$config['composer_autoload'] = FALSE;</code> with <code>$config['composer_autoload'] = 'vendor/autoload.php';</code> in the <code>config.php</code> file.

**Comment by mtnsosa** [comment]
i dont have the line `$config['composer_autoload'] = FALSE;`. I only have `$config['composer_autoload'] = 'vendor/autoload.php';`

**Comment by mtnsosa** [comment]
SORRY! SORRY! what im doing is in `application/autoload.php` instead of `application/config.php`. Replce `$config['composer_autoload'] = FALSE;` with `$config['composer_autoload'] = 'vendor/autoload.php';` works! thank you so much!

**Comment by egarofalo** [comment]
Great!!! You welcome!
